In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
print("Numpy Version:",np.__version__)
print("Pandas version:",pd.__version__)

Numpy Version: 2.1.3
Pandas version: 2.2.3

In [ ]:
marks = np.array([78,85,92,67,88])
print("Marks:",marks)
print("Type:",type(marks))

Marks: [78 85 92 67 88]
Type: <class 'numpy.ndarray'>

In [ ]:
marks = np.array([78,85,92,67,88])
print("Number of dimension:",marks.ndim)
print("Shape:",marks.shape)
print("Number of element:",marks.size)

Number of dimension: 1
Shape: (5,)
Number of element: 5

In [ ]:
marks = np.array([78,85,92,67,88])
print("Original:",marks)
print("Add 5:",marks+5)
print("Multiply by 2:",marks*2)
print("Divided by 2:",marks/2)

print("Square :",marks**2)

Original: [78 85 92 67 88]
Add 5: [83 90 97 72 93]
Multiply by 2: [156 170 184 134 176]
Divided by 2: [39.  42.5 46.  33.5 44. ]
Square : [6084 7225 8464 4489 7744]

In [ ]:
marks = np.array([78,85,92,67,88])
print("sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())
print("Minimum:",marks.min())

sum: 410
Mean: 82.0
Maximum: 92
Minimum: 67

In [ ]:
marks = np.array([78,85,92,67,88])
print("First mark:",marks[0])
print("Second mark:",marks[1])
print("Last mark:",marks[-1])

First mark: 78
Second mark: 85
Last mark: 88

In [ ]:
marks = np.array([78,85,92,67,88])
print("Index 1 to 3",marks[1:4])
print("First Three:",marks[:3])
print("From Index 2:",marks[2:])
print("Every Second Index:",marks[::2])

Index 1 to 3 [85 92 67]
First Three: [78 85 92]
From Index 2: [92 67 88]
Every Second Index: [78 92 88]

In [ ]:
student_marks=np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
])

print(student_marks)
print("Shape:",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)

In [ ]:
print("Mean of all values:",student_marks.mean())
print("Column_wise Mean:",student_marks.mean(axis=0))
print("Row-wise Mean:",student_marks.mean(axis=1))
print("Dimension:",student_marks.ndim)

Mean of all values: 84.44444444444444
Column_wise Mean: [78.33333333 89.33333333 85.66666667]
Row-wise Mean: [85.         77.         91.33333333]
Dimension: 2

In [ ]:
data = {
    "Name": ["Anu","Rahul","Kiran","Priya"],
    "Branch": ["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88]
}

df = pd.DataFrame(data)
print(df)

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.head()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:

data = {
    "Name": ["Anu","Rahul","Kiran","Priya"],
    "Branch": ["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88]
}
df = pd.DataFrame(data)
print(df)
print("Shape:", df.shape)
print("Column:",df.columns)

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88
Shape: (4, 3)
Column: Index(['Name', 'Branch', 'Marks'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

           Marks
count   4.000000
mean   85.000000
std     6.480741
min    76.000000
25%    82.750000
50%    86.500000
75%    88.750000
max    91.000000

In [ ]:
print(df["Name"])
print(df["Marks"])
print(df["Branch"])
print(df[["Branch","Marks"]])

0      Anu
1    Rahul
2    Kiran
3    Priya
Name: Name, dtype: object
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64
0     CSE
1    AIML
2     CSE
3    AIML
Name: Branch, dtype: object
  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88

In [ ]:
print("First Row:\n",df.iloc[0]) #integer location

First Row:
 Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

In [ ]:
print("Second Row:\n",df.iloc[1])
print("Thrid Row:\n",df.iloc[2])

Second Row:
 Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object
Thrid Row:
 Name      Kiran
Branch      CSE
Marks        76
Name: 2, dtype: object

In [ ]:
print("First three Row:\n",df.iloc[0:3])

First three Row:
     Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

In [ ]:
print("First two Row an dfisrt column:\n",df.iloc[0:2 , 0:2])

First two Row an dfisrt column:
     Name Branch
0    Anu    CSE
1  Rahul   AIML

In [ ]:
print("Rows 1 to 3 , Name and Marks:\n",df.iloc[1:4 , 0:3:2]) # fisrt indexing is for rows and second indexing is for column

Rows 1 to 3 , Name and Marks:
     Name  Marks
1  Rahul     91
2  Kiran     76
3  Priya     88

In [ ]:
high_scorers = df[df["Marks"]>90]
high_scorers

    Name Branch  Marks
1  Rahul   AIML     91

In [ ]:
print("Student  from CSE:")
display(df[df["Branch"]=="CSE"])
print("Student Scoring 85 or more:")
display(df[df["Marks"] >= 85])

Student  from CSE:

    Name Branch  Marks
0    Anu    CSE     85
2  Kiran    CSE     76

Student Scoring 85 or more:

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88

In [ ]:
data = {
    "Name": ["Ahsa","Bahart","Chetan","Divya","Esha"],
    "Branch": ["CSE","ISE","CSE","AIML","ISE"],
    "Marks":[72,91,84,95,68],
    "Attendance":[82,94,88,96,75]
}
students = pd.DataFrame(data)
students

     Name Branch  Marks  Attendance
0    Ahsa    CSE     72          82
1  Bahart    ISE     91          94
2  Chetan    CSE     84          88
3   Divya   AIML     95          96
4    Esha    ISE     68          75

In [ ]:
print(students["Name"])
print(students["Marks"])

0      Ahsa
1    Bahart
2    Chetan
3     Divya
4      Esha
Name: Name, dtype: object
0    72
1    91
2    84
3    95
4    68
Name: Marks, dtype: int64

In [ ]:
print("student scoring more than 80:")
display(students[students["Marks"]>80])

student scoring more than 80:

     Name Branch  Marks  Attendance
1  Bahart    ISE     91          94
2  Chetan    CSE     84          88
3   Divya   AIML     95          96

In [ ]:
print("Student attendance more than 85 percentage:")
display(students[students["Attendance"]>85])

Student attendance more than 85 percentage:

     Name Branch  Marks  Attendance
1  Bahart    ISE     91          94
2  Chetan    CSE     84          88
3   Divya   AIML     95          96

In [ ]:
print("First three Students :\n",students[0:3])

First three Students :
      Name Branch  Marks  Attendance
0    Ahsa    CSE     72          82
1  Bahart    ISE     91          94
2  Chetan    CSE     84          88

In [ ]:
print("Average of marks:",students["Marks"].mean())

Average of marks: 82.0

In [ ]:
print("Maximum Marks:",students["Marks"].max())

Maximum Marks: 95

In [ ]:
print("Students from only CSE Branch:",students[students["Branch"]=="CSE"])

Students from only CSE Branch:      Name Branch  Marks  Attendance
0    Ahsa    CSE     72          82
2  Chetan    CSE     84          88

In [ ]:
print("Student scored atleast 80 and having tne attendance 85 percentage:")
display(students[(students["Marks"]>=80) & (students["Attendance"]>85)])

Student scored atleast 80 and having tne attendance 85 percentage:

     Name Branch  Marks  Attendance
1  Bahart    ISE     91          94
2  Chetan    CSE     84          88
3   Divya   AIML     95          96